# Generated by Django 5.0.1 on 2024-01-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
